### ISSUE TITLE
YOLOv8模型改进 融合BiFPN模块

### ISSUE THREAD

**Issue by yangershuai627** [yangershuai627/yolov8#12]
# 一、模型的配置文件
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 Oriented Bounding Boxes (OBB) model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 20 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [ -1, 1, Conv, [ 512, 1, 1 ] ]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, BiFPN_Add2, [1024, 128]]  # 将这里的 256 改为 128
  - [-1, 3, C2f, [512]]  # 13

  - [-1, 1, Conv, [256, 1, 1]]
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, BiFPN_Add2, [128, 128]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 17 (P3/8-small)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 13, 6], 1, BiFPN_Add3, [256, 256]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 20 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, BiFPN_Add2, [256, 256]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 23 (P5/32-large)

  - [[17, 20, 23], 1, OBB, [nc, 1]]  # Detect(P3, P4, P5)
```
# 二、在ultralytics/nn/modules下创建BiFPN.py

![Image](https://github.com/user-attachments/assets/f84eb3cb-28e6-4c1b-9576-d8211bc36265)
## BiFPN.py:
```
# BiFPN
# 两个特征图add操作
import torch.nn as nn
import torch

class BiFPN_Add2(nn.Module):
	def __init__(self, c1, c2):
		super(BiFPN_Add2, self).__init__()
		# 设置可学习参数 nn.Parameter的作用是：将一个不可训练的类型Tensor转换成可以训练的类型parameter
		# 并且会向宿主模型注册该参数 成为其一部分 即model.parameters()会包含这个parameter
		# 从而在参数优化的时候可以自动一起优化
		self.w = nn.Parameter(torch.ones(2, dtype=torch.float32), requires_grad=True)
		self.epsilon = 0.0001
		self.conv = nn.Conv2d(c1, c2, kernel_size=1, stride=1, padding=0)
		self.silu = nn.SiLU()

	def forward(self, x):
		x0, x1 = x
		w = self.w
		weight = w / (torch.sum(w, dim=0) + self.epsilon)
		return self.conv(self.silu(weight[0] * x0 + weight[1] * x1))


# 三个特征图add操作
class BiFPN_Add3(nn.Module):
	def __init__(self, c1, c2):
		super(BiFPN_Add3, self).__init__()
		self.w = nn.Parameter(torch.ones(3, dtype=torch.float32), requires_grad=True)
		self.epsilon = 0.0001
		self.conv = nn.Conv2d(c1, c2, kernel_size=1, stride=1, padding=0)
		self.silu = nn.SiLU()

	def forward(self, x):
		w = self.w
		weight = w / (torch.sum(w, dim=0) + self.epsilon)
		# Fast normalized fusion
		return self.conv(self.silu(weight[0] * x[0] + weight[1] * x[1] + weight[2] * x[2]))
	
```
# 三、在task.py中导入

![Image](https://github.com/user-attachments/assets/78d392e5-273d-496b-bac2-715633e4807a)

![Image](https://github.com/user-attachments/assets/6d453a09-0899-404e-9177-64d75a2af70c)

# 四、训练模型

![Image](https://github.com/user-attachments/assets/d79c1564-f811-4fc5-9f82-16c40bcd4ac8)
