### ISSUE TITLE
YOLOv8模型改进 添加全局注意力机制GAM

### ISSUE THREAD

**Issue by yangershuai627** [yangershuai627/yolov8#38]
# 一、Preference
https://blog.csdn.net/qq_44224801/article/details/130059070?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7Ebaidujs_baidulandingword%7EPaidSort-1-130059070-blog-136353061.235%5Ev43%5Epc_blog_bottom_relevance_base3&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7Ebaidujs_baidulandingword%7EPaidSort-1-130059070-blog-136353061.235%5Ev43%5Epc_blog_bottom_relevance_base3&utm_relevant_index=1
# 二、添加GAM
## GAM.py：
```
import torch.nn as nn
import torch
 
class GAM_Attention(nn.Module):
    def __init__(self, in_channels,c2, rate=4):
        super(GAM_Attention, self).__init__()
 
        self.channel_attention = nn.Sequential(
            nn.Linear(in_channels, int(in_channels / rate)),
            nn.ReLU(inplace=True),
            nn.Linear(int(in_channels / rate), in_channels)
        )
 
        self.spatial_attention = nn.Sequential(
            nn.Conv2d(in_channels, int(in_channels / rate), kernel_size=7, padding=3),
            nn.BatchNorm2d(int(in_channels / rate)),
            nn.ReLU(inplace=True),
            nn.Conv2d(int(in_channels / rate), in_channels, kernel_size=7, padding=3),
            nn.BatchNorm2d(in_channels)
        )
 
    def forward(self, x):
        b, c, h, w = x.shape
        x_permute = x.permute(0, 2, 3, 1).view(b, -1, c)
        x_att_permute = self.channel_attention(x_permute).view(b, h, w, c)
        x_channel_att = x_att_permute.permute(0, 3, 1, 2).sigmoid()
        x = x * x_channel_att
        x_spatial_att = self.spatial_attention(x).sigmoid()
        out = x * x_spatial_att
 
        return out
 
if __name__ == '__main__':
    x = torch.randn(1, 64, 20, 20)
    b, c, h, w = x.shape
    net = GAM_Attention(in_channels=c)
    y = net(x)
    print(y.size())
```
## （二）在tasks.py中导入
`from ultralytics.nn.modules.GAM import GAM_Attention`
```
elif m is GAM_Attention:
    c1, c2 = ch[f], args[0]
    if c2 != nc:
        c2 = make_divisible(min(c2, max_channels) * width, 8)
    args = [c1, c2, *args[1:]]
```
## （三）修改模型的配置文件
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 Oriented Bounding Boxes (OBB) model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 20 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]                  # 假设输入特征图的大小是3×640×640
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2             # 64×320×320
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4            # 128×160×160
  - [-1, 3, C2f, [128, True]]                      # 128×160×160
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8            # 256×80×80
  - [-1, 6, C2f, [256, True]]                      # 256×80×80
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16           # 512×40×40
  - [-1, 6, C2f, [512, True]]                      # 512×40×40
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32          # 1024×20×20
  - [-1, 3, C2f, [1024, True]]                     # 1024×20×20
  - [-1, 1, GAM_Attention, [1024]] # 9             # 1024×20×20
  - [-1, 1, SPPF, [1024, 5]] # 10                   # 1024×20×20

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]     # 1024×40×40
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4    # 512+1024=1536×40×40
  - [-1, 3, C2f, [512]] # 13                       # 512×40×40

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]     # 512×80×80
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3    # 256+512=768×80×80
  - [-1, 3, C2f, [256]] # 16 (P3/8-small)          # 256×80×80

  - [-1, 1, Conv, [256, 3, 2]]                     # 256×40×40
  - [[-1, 13], 1, Concat, [1]] # cat head P4       # 256+512=768×40×40
  - [-1, 3, C2f, [512]] # 19 (P4/16-medium)        # 512×40×40

  - [-1, 1, Conv, [512, 3, 2]]                     # 512×20×20
  - [[-1, 10], 1, Concat, [1]] # cat head P5        # 512+1024=1536×20×20
  - [-1, 3, C2f, [1024]] # 22 (P5/32-large)        # 1024×20×20

  - [[16, 19, 22], 1, OBB, [nc, 1]] # OBB(P3, P4, P5)
```
# 三、训练模型

![Image](https://github.com/user-attachments/assets/d4ed40b3-63f9-47cf-b2fb-f57e57ea8d98)

![Image](https://github.com/user-attachments/assets/674df15b-35ec-486d-a32f-8c4bb1afaf62)
